### ISSUE TITLE
Position data included when `verbose` is false

### ISSUE THREAD

**Issue by Josmithr** [syntax-tree/hast-util-from-html#7]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

hast-util-from-html@2.0.3

### Steps to reproduce

```typescript
import { fromHtml } from "hast-util-from-html";

const htmlTree = fromHtml("This is some <b>bold</b> text!", { fragment: true, verbose: false });
```

### Expected behavior

The expected output should not contain position information, per the documentation on the `verbose` parameter, but it does.

### Actual behavior

Position information included in generated HAST tree.

### Affected runtime and version

node@18.19.1

### Affected package manager and version

npm@10.2.4

### Affected OS and version

Linux

**Comment by wooorm** [comment]
That is intentional.
You can remove positional info if you want: https://github.com/syntax-tree/unist-util-remove-position.

**Comment by wooorm** [comment]
The important parts in the docs are: “Add ***extra*** positional info about ***attributes, start tags, and end tags***.
